version: '3.8'

services:
  spring-boot:
    restart: 'on-failure'
    build:
      context: './Module-API'
      dockerfile: Dockerfile
      args:
        PROFILE: local
        JMX_PORT: 9010
    container_name: 'module-api-server'
    ports:
      - '8080:8080'
      - '9010:9010'
    depends_on:
      - redis
  redis:
    restart: 'on-failure'
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"